### ISSUE TITLE
Milestone 2 - Python functions (high priority)

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/CorrPy#26]
The following summaries expectations for this milestone:
- 3 Python function （by Feb 12th.)
- [x] std_plus (Albert)
- [x] corr_plus (Wilson)
- [x] cov_mx 
(While doing this, if you think of new test cases you are not required to write the new tests but instead create an issue for them which you can complete during milestone 3.)

**Following GitHub Flow workflow**

Starting from this milestone, you must follow the GitHub Flow workflow. Each team member must do at least one review and each member must have some part of their code reviewed by other team members.
- [x] Kera
- [x] Krish 
- [x] Wilson  
- [x] Albert

 In particular, each team member will

- create a branch
- work on the function you are responsible for in this branch
- add commits
- open a pull request (you should be at this step by the end of the lab on Feb 12th)
- wait for the code review and feedback from other team member
- review code of other team member via their pull request
- deploy your changes
- merge if your branch is not causing any problems

---

Just some notes:
1. In order to improve our coding format, it is better to limit to 120 characters per line. For further information, please read https://stackoverflow.com/questions/88942/why-does-pep-8-specify-a-maximum-line-length-of-79-characters
2. To toggle the warning line in Studio. https://support.rstudio.com/hc/en-us/community/posts/207625357-Toggle-80-character-warning-line
3. For atom. https://stackoverflow.com/questions/49616864/limiting-line-length-in-atom
4. For VS code. https://stackoverflow.com/questions/29968499/vertical-rulers-in-visual-studio-code

**Comment by xiaoweideng** [comment]
Hey guys,
I just finished `corr_plus` and fixed the test values for `test_corr_plus`. I will send a pull request tomorrow. :wink:
