### ISSUE TITLE
Milestone 3 - Documentation in CorrPy

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/CorrPy#41]
- Documentation
- [x] Py package README (including usage and installation instructions)
`pip install git+PACKAGE_URL.git`
`devtools::install_github("PACKAGE_NAME")` for R packages
- [x] Code documentation 
- [x] ensure that the test suite for each function provides 100% branch coverage (if possible). Please include documentation (e.g. as we did on the board in class) that shows you've checked for this.
- [x] functions
- [x] tests

**Comment by mru4913** [comment]
I just realised we should improve the branch coverage algorithm. We will do it later.

**Comment by K3ra-y** [comment]
Milestone 3 is complete.

**Comment by mru4913** [comment]
Hi @hsmohammed,

Please close the issue after you read our workflow.
