### ISSUE TITLE
Milestone 02 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/CorrPy#42]
Hello,

- I see that you are on track and did everything required in Milestone 02.
- The package setup and tests run without any problems
- You have efficiently used github workflow efficiently including branching, issue tracker,...
- I suggest you relocate your tests folder to the main directory to comply with the conventions

Thanks!

**Comment by mru4913** [comment]
@hsmohammed 

 Thank you for your feedback.
